services:
  app:
    build:
      context: .
      target: production
    container_name: nestjs_app
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
